#!/usr/bin/env bash

image_id="$(aws ec2 describe-images --filters "Name=name, Values=base-${BUILD_VERSION}" | jq .Images[0].ImageId)"

source ~/.secrets/packer/play && \
        packer build  \
        -only app-ami \
        -var "source_ami=${image_id}"
        -var-file template-app-ami.json packer-aws.json > packer.log
