#!/usr/bin/env bash

# shellcheck source=/dev/null
source ~/.secrets/build/packer-build

packer build \
        -only build-ami \
        -var-file template-build-ami.json \
        packer-build.json 
