#!/usr/bin/env bash

# shellcheck source=/dev/null
source ~/.secrets/build/packer

packer build \
        -only base-ami \
        -var-file template-base-ami.json \
        packer-aws.json > packer.log
