#!/usr/bin/env bash

# shellcheck source=/dev/null
source ~/.secrets/build/packer || exit

AMI_ID="$(aws ec2 describe-images --filters "Name=name, Values=base-${BUILD_VERSION}" | jq .Images[0].ImageId | tr -d '"')"

echo "Building from ${AMI_ID}"
packer build  \
        -debug \
        -only app-ami \
        -var "source_ami=${AMI_ID}" \
        -var-file template-app-ami.json packer-aws.json
